[meta]
    language = "Français"
    variant = "France"
    shorthand = "fr-FR"
    mapped_name = "fr"

[commands]
    [commands.@COMMANDS_CLEARID@]
        name = "effacer"
        desc = "nettoie l'écran"
    [commands.@COMMANDS_ECHOID@]
        name = "echo"
        desc = "affiche du texte à l'écran"
    [commands.@COMMANDS_EXITID@]
        name = "sortir"
        desc = "ferme le terminal"
    [commands.@COMMANDS_HELPID@]
        name = "aide"
        desc = "affiche cette aide"
    [commands.@COMMANDS_PRINTID@]
        name = "impr"
        desc = "affiche du texte à l'écran"
    [commands.@COMMANDS_QUITID@]
        name = "quitter"
        desc = "ferme l’application"
    [commands.@COMMANDS_LOAD_DLLID@]
        name = "charge_lib"
        desc = "charge une bilbiothèque pour gérer le roBot"
    [commands.@COMMANDS_LOAD_MAPID@]
        name = "charge_carte"
        desc = "charge une carte depuis un fichier"
    [commands.@COMMANDS_UPDATE_WORLDID@]
        name = "tick"
        desc = "avance le monde d’un tick dans le temps"
    [commands.@COMMANDS_SETID@]
        name = "majv"
        desc = "met à jour la valeur d’une variable"
    [commands.@COMMANDS_VALUEOFID@]
        name = "valv"
        desc = "affiche la valeur d'une variable"
    [commands.@COMMANDS_RELOAD_RESOURCES@]
        name = "config"
        desc = "recharge les fichiers de resources et de configuration"
    [commands.@COMMANDS_FIRE_ACTIONABLE@]
        name = "actionner"
        desc = "Envoie un signal à un actionnable (ex : ouvrir/fermer une porte)"
    [commands.@COMMANDS_FIRE_ACTIVATOR@]
        name = "activer"
        desc = "Envoie un signal à un activateur (ex : appuyer sur un bouton)"

[variables]
    [variables.@VARIABLES_AVERAGE_FPSID@]
        name = "fps_moyen"
    [variables.@VARIABLES_TARGET_FPSID@]
        name = "fps_cible"
    [variables.@VARIABLES_DISPLAY_DEBUG_DATAID@]
        name = "afficher_indices_debogage"

[log]
    [[log.entry]]
        id = "terminal_commands.command_missing_name"
        fmt = "La commande {cmd_id} n’est associée à aucun nom d’appel"

    [[log.entry]]
        id = "terminal_commands.load_dll.usage"
        fmt = "Utilisation : {arg0} <chemin vers la bibliothèque>"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading"
        fmt = "{dll_path} : chargement en cours"
    [[log.entry]]
        id = "terminal_commands.load_dll.loading_failed"
        fmt = "Échec du chargement"

    [[log.entry]]
        id = "terminal_commands.load_map.usage"
        fmt = "Utilisation : {arg0} <chemin vers la carte>"

    [[log.entry]]
        id = "terminal_commands.set.usage"
        fmt = "Utilisation : {arg0} <variable> <valeur>"
    [[log.entry]]
        id = "terminal_commands.set.unknown_var"
        fmt = "{var_name} : variable non reconnue"
    [[log.entry]]
        id = "terminal_commands.set.need_uint"
        fmt = "{value} n’est pas un entier positif"
    [[log.entry]]
        id = "terminal_commands.set.is_read_only"
        fmt = "Erreur : {var_name} est en lecture seule"

    [[log.entry]]
        id = "terminal_commands.get.usage"
        fmt = "Utilisation : {arg0} <variable>"
    [[log.entry]]
        id = "terminal_commands.get.unknown_var"
        fmt = "{var_name} : variable non reconnue"

    [[log.entry]]
        id = "terminal_commands.reload.usage"
        fmt = "Utilisation : {arg0} <fichier de config>"
    [[log.entry]]
        id = "terminal_commands.reload.fail"
        fmt = "Erreur lors du chargement du fichier {file_path}"
    [[log.entry]]
        id = "terminal_commands.reload.success"
        fmt = "{file_path}: configuration chargée avec succès"

    [[log.entry]]
        id = "terminal_commands.fire_activator.usage"
        fmt = "Utilisation : {arg0} <id d’activateur>"
    [[log.entry]]
        id = "terminal_commands.fire_activator.need_uint"
        fmt = "Erreur : l’id \"{value}\" n’est pas un entier positif"
    [[log.entry]]
        id = "terminal_commands.fire_activator.too_high"
        fmt = "Erreur : l’id {value} dépasse la valeur maximale autorisée pour la carte (max: {max_value})"
    [[log.entry]]
        id = "terminal_commands.fire_activator.none"
        fmt = "Erreur : il' n'y a pas d'activateur sur cette carte"

    [[log.entry]]
        id = "terminal_commands.general.help"
        fmt = "Commandes disponibles :"

    [[log.entry]]
        id = "terminal_commands.fire_actionable.usage"
        fmt = "Utilisation: {arg0} <id d'actionable>"
    [[log.entry]]
        id = "terminal_commands.fire_actionable.need_uint"
        fmt = "Erreur : l'id \"{value}\" n’est pas un entier positif valide"
    [[log.entry]]
        id = "terminal_commands.fire_actionable.too_high"
        fmt = "Erreur : l'id {value} dépasse la valeur maximale autorisée pour la carte (max: {max_value})"
    [[log.entry]]
        id = "terminal_commands.fire_actionable.none"
        fmt = "Erreur : il' n'y a pas d'actionable sur cette carte"

    [[log.entry]]
        id = "state_holder.configure.config_load_failed"
        fmt = "Échec du chargement des resources (fichier : {file})"

    [[log.entry]]
        id = "overmap_collection.unknow_entity_move"
        fmt = "Tentative de déplacement d’une entité inconnue {{type: vue, is_mob:{is_mob}, handle:{handle}}}"
    [[log.entry]]
        id = "overmap_collection.moving_mob"
        fmt = "Déplacement du mob [id vue] {handle} vers ({x} ; {y})"
    [[log.entry]]
        id = "overmap_collection.moving_object"
        fmt = "Déplacement de l’objet [id vue] {handle} vers ({x} ; {y})"
    [[log.entry]]
        id = "overmap_collection.incompatible_rotate"
        fmt = "Demande de rotation pour un objet incompatible [id vue] {handle}"

    [[log.entry]]
        id = "actionable.none"
        fmt = "({x} ; {y}) : rien à activer ici"
    [[log.entry]]
        id = "actionable.gate.open"
        fmt = "Ouverture de porte en ({x} ; {y})"
    [[log.entry]]
        id = "actionable.gate.close"
        fmt = "Fermeture de porte en ({x} ; {y})"

    [[log.entry]]
        id = "bot_api.commit.invalid_handle"
        fmt = "[DLL] Identifiant cible {handle} invalide pour la décision {decision}"
    [[log.entry]]
        id = "bot_api.commit.sanitize"
        fmt = "[DLL] Valeur flotante {value} invalide pour le paramètre {parameter}"

    [[log.entry]]
        id = "bot_dll.required_load_failed"
        fmt = "Le chargement de la fonction {func_name} a échoué (fichier {file})"
    [[log.entry]]
        id = "bot_dll.optional_load_failed"
        fmt = "Fonction facultative {func_name} non présente dans {file}"
    [[log.entry]]
        id = "bot_dll.optional_load_success"
        fmt = "Fonction facultative {func_name} chargée depuis {file}"
    [[log.entry]]
        id = "bod_dll.reload.no_path"
        fmt = "Échec du chargement de la dll : chemin d’accès vide."
    [[log.entry]]
        id = "bot_dll.load.failed"
        fmt = "Échec du chargement de la dll \"{file}\": {error}"
    [[log.entry]]
        id = "bot_dll.load.bad_abi"
        fmt = "Échec du chagement de la dll \"{file}\": ABI non valide"

    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.unknown_mob_reference"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : le mob {mob} est utilisé avant sa déclaration"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_missing_name"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : nom manquant pour un mob (clef: {key})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_missing_hp"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : PV non spécifiés pour le mob {name} (clef: {key})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_missing_sprite"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : sprite non spécifié pour le mob {name} (clef: {key})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_missing_behaviour"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : comportement non spécifié pour le mob {name} (clef: {key})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_with_unknown_type"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : type non spécifié pour un mob (clef: {})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_type_not_recognized"
        fmt = "(type spécifié ({type}) non reconnu)"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.mob_spawn_missing_component"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : la clef {key} est manquante (lors du chargement des information de la section 'spawn') (type de mob : {type})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_with_unknown_type"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : clef '{key}' manquante pour un acteur (type de l’acteur inconnu)"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_missing_component"
        fmt = "Erreur lors du chargement de la carte\"{map}\" : clef '{key}' manquante pour un acteur (type de l’acteur : {type})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_duplication"
        fmt = "Attention : l’acteur '{actor}' est dupliqué (dans la carte \"{map}\")"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_with_unrecognized_type"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : le type d’acteur '{type}' n’est pas connu (clef: {key})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_with_no_target"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : un acteur de type '{type}' n’a pas de cible sur laquelle agir (clef : {key}) (la valeur est peut-être malformée)"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.actor_with_unknown_target"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : un acteur de type '{type}' à pour cible \"{target}\", qui n’est pas connue"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.missing_mob_def"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : section 'mobs.definition' est maquante"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.missing_mob_placings"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : section 'mobs.spawn' manquante"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.missing_actors"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : section 'actors.spawn' manquante"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.missing_map_layout"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : entrée 'map.layout' manquante"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.map_loaded"
        fmt = "carte \"{map}\" chargée"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.internal_error"
        fmt = "Erreur interne lors du chargement de la carte \"{map}\""
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.bad_mob_defs"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : définition invalide de 'mobs.definition'"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.bad_mob_spawns"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : section 'spawns' invalide"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.too_many_spawns"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : trop d'éléments dans la section 'spawns'"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.empty_map"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : taille de carte nulle"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.bad_map_size"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : les dimensions ne sont pas cohérentes (à la ligne {line})"
    [[log.entry]]
        id = "adapter_map_loader_v1_0_0.bad_map_char"
        fmt = "Erreur lors du chargement de la carte \"{map}\" : caractère inconnu '{char}' dans la définition de la carte ({line}:{column})"

    [[log.entry]]
        id = "adapter.map_load_failure"
        fmt = "Erreur lors du chargement de la carte \"{path}\" : {reason}"
    [[log.entry]]
        id = "adapter.unsupported_version"
        fmt = "Version '{version}' non supportée pour la carte \"{path}\""
    [[log.entry]]
        id = "adapter.unknown_model_handle"
        fmt = "Id modèle inconnue ({model_handle}) pour l'opération '{operation}'"
    [[log.entry]]
        id = "adapter.trace.rotate_entity"
        fmt = "Rotation de l'entité vue {view_handle}. Nouvel angle de {angle} radians"
    [[log.entry]]
        id = "adapter.name_not_found"
        fmt = "Nom introuvable pour {kind} {handle}"
    [[log.entry]]
        id = "adapter.non_coherent_entity"
        fmt = "Type d'entité incohérent pour {handle}. La logique et la vue n'ont peut-être pas été synchronisés correctement (erreur interne)"
    [[log.entry]]
        id = "adapter.unknown_view_entity"
        fmt = "L'entité vue {view_handle} est introuvable. La logique et la vue n'ont peut-être pas été synchronisés correctement (erreur interne)"

    [[log.entry]]
        id = "resource_manager.commands_texts.reload_failed"
        fmt = "Échec lors du rechargement du nom des commandes"
    [[log.entry]]
        id = "resource_manager.gui_texts.reload_failed"
        fmt = "Échec lors du rechargement des textes de l’interface"
    [[log.entry]]
        id = "resource_manger.log_texts.reload_failed"
        fmt = "Échec lors du rechargement des textes de log"
    [[log.entry]]
        id = "resource_manager.resource_pack.reload_failed"
        fmt = "Échec lors du rechargement des textures"

    [[log.entry]]
        id = "view.view.menu.unknown_request"
        fmt = "Requête inconnue reçue depuis le menu : {id}"
    [[log.entry]]
        id = "view.view.bad_state"
        fmt = "État de la vue inconnu : {state}"
    [[log.entry]]
        id = "view.view.FA_load_failed"
        fmt = "Échec de chargement de Font Awesome depuis \"{folder}\""
    [[log.entry]]
        id = "view.view.FA_load_success"
        fmt = "Font Awesome chargée avec succès"

    [[log.entry]]
        id = "view.terminal.regex_filter"
        fmt = "filtre regex..."

    [[log.entry]]
        id = "view.configurator.config_save_failed"
        fmt = "Échec de sauvegarde de la configuration"

[tooltip]
    [[tooltip.entry]]
        id = "adapter.objective"
        fmt = "Ton objectif."
    [[tooltip.entry]]
        id = "adapter.hp"
        fmt = "PV: {hp}"
    [[tooltip.entry]]
        id = "adapter.hitbox"
        fmt = "Boîte de collision: ({top_left_x} ; {top_left_y}) à ({bottom_right_x} ; {bottom_right_y})"
    [[tooltip.entry]]
        id = "adapter.position"
        fmt = "Position: ({x} ; {y})"
    [[tooltip.entry]]
        id = "adapter.angle"
        fmt = "Angle: {angle}"
    [[tooltip.entry]]
        id = "adapter.activator"
        fmt = "Activateur: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_target"
        fmt = "Cible: {handle}, \"{name}\""
    [[tooltip.entry]]
        id = "adapter.nameless_target"
        fmt = "Cible: {handle}"
    [[tooltip.entry]]
        id = "adapter.named_gate"
        fmt = "Portail: {handle}, \"{name}\""
    [[tooltip.entry]]
        id = "adapter.nameless_gate"
        fmt = "Portail: {handle}"

[gui]
    [[gui.entry]]
        id = "view.in_game_menu.resume"
        fmt = "Reprendre"
    [[gui.entry]]
        id = "view.in_game_menu.dll"
        fmt = "Infuser de l'intelligence"
    [[gui.entry]]
        id = "view.in_game_menu.restart"
        fmt = "Recommencer"
    [[gui.entry]]
        id = "view.in_game_menu.settings"
        fmt = "Paramètres"
    [[gui.entry]]
        id = "view.in_game_menu.import_maps"
        fmt = "Importer des cartes"
    [[gui.entry]]
        id = "view.in_game_menu.load_map"
        fmt = "Charger une carte"
    [[gui.entry]]
        id = "view.in_game_menu.quit"
        fmt = "Quitter"
    [[gui.entry]]
        id = "view.in_game_menu.credits"
        fmt = "Credits"
    [[gui.entry]]
        id = "view.in_game_menu.map_editor"
        fmt = "Éditeur de carte"
    [[gui.entry]]
        id = "view.in_game_menu.campaign_editor"
        fmt = "Éditeur de campagne"
    [[gui.entry]]
        id = "view.in_game_menu.return_to_main_menu"
        fmt = "Menu principal"

    [[gui.entry]]
        id = "file_explorer.ok_button"
        fmt = "OK"
    [[gui.entry]]
        id = "file_explorer.cancel_button"
        fmt = "Annuler"

    [[gui.entry]]
        id = "configurator.general_lang"
        fmt = "Langue générale : "
    [[gui.entry]]
        id = "configurator.command_lang"
        fmt = "Langue de commandes : "
    [[gui.entry]]
        id = "configurator.gui_lang"
        fmt = "Langue de l’interface : "
    [[gui.entry]]
        id = "configurator.log_lang"
        fmt = "Langue de log : "
    [[gui.entry]]
        id = "configurator.resource_pack"
        fmt = "Habillage graphique : "
    [[gui.entry]]
        id = "configurator.import_respack"
        fmt = "Importer des textures"
    [[gui.entry]]
        id = "configurator.import_lang"
        fmt = "Importer une langue"
