#ifndef NINJACLOWN_UTILS_MACROS_HPP
#define NINJACLOWN_UTILS_MACROS_HPP

#define NINJACLOWN_CONCAT_IMPL(x, y) x##y
#define NINJACLOWN_CONCAT(x, y) NINJACLOWN_CONCAT_IMPL(x,y)

#ifndef __COUNTER__
#define __COUNTER__ __LINE__
#warning "Somewhat unknown compiler"
#endif

#define NINJACLOWN_MAKE_VAR_NAME NINJACLOWN_CONCAT(impl_autogenerated_named_temporary,__COUNTER__)

#endif //NINJACLOWN_UTILS_MACROS_HPP
