[meta]
    name.dflt_lang = "en"
    name.en = "programmer - simple 2D"
    name.fr = "programmeur - 2D simple"

[graphics]
    file = "assets.png"

    [graphics.mobs]
        list = ["dll", "harmless", "patrol", "aggressive"]

        [graphics.mobs.dll]
            id = @MOBS_DLLID@
    
            [graphics.mobs.dll.downwards]
                frame-count = 1
                pos.x = 192
                pos.y = 16
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.upwards]
                frame-count = 1
                pos.x = 208
                pos.y = 16
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.rightwards]
                frame-count = 1
                pos.x = 208
                pos.y = 0
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.leftwards]
                frame-count = 1
                pos.x = 192
                pos.y = 0
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.uprightwards]
                frame-count = 1
                pos.x = 240
                pos.y = 0
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.upleftwards]
                frame-count = 1
                pos.x = 224
                pos.y = 0
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.downrightwards]
                frame-count = 1
                pos.x = 240
                pos.y = 16
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.dll.downleftwards]
                frame-count = 1
                pos.x = 224
                pos.y = 16
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16


        [graphics.mobs.harmless]
            id = @MOBS_HARMLESSID@
    
            [graphics.mobs.harmless.downwards]
                frame-count = 1
                pos.x = 192
                pos.y = 48
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.upwards]
                frame-count = 1
                pos.x = 208
                pos.y = 48
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.rightwards]
                frame-count = 1
                pos.x = 208
                pos.y = 32
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.leftwards]
                frame-count = 1
                pos.x = 192
                pos.y = 32
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.uprightwards]
                frame-count = 1
                pos.x = 240
                pos.y = 32
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.upleftwards]
                frame-count = 1
                pos.x = 224
                pos.y = 32
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.downrightwards]
                frame-count = 1
                pos.x = 240
                pos.y = 48
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.harmless.downleftwards]
                frame-count = 1
                pos.x = 224
                pos.y = 48
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16

        [graphics.mobs.patrol]
            id = @MOBS_PATROLID@
    
            [graphics.mobs.patrol.downwards]
                frame-count = 1
                pos.x = 0
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.upwards]
                frame-count = 1
                pos.x = 16
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.rightwards]
                frame-count = 1
                pos.x = 16
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.leftwards]
                frame-count = 1
                pos.x = 0
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.uprightwards]
                frame-count = 1
                pos.x = 48
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.upleftwards]
                frame-count = 1
                pos.x = 32
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.downrightwards]
                frame-count = 1
                pos.x = 48
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.patrol.downleftwards]
                frame-count = 1
                pos.x = 32
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16

        [graphics.mobs.aggressive]
            id = @MOBS_AGGRESSIVEID@
    
            [graphics.mobs.aggressive.downwards]
                frame-count = 1
                pos.x = 64
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.upwards]
                frame-count = 1
                pos.x = 80
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.rightwards]
                frame-count = 1
                pos.x = 80
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.leftwards]
                frame-count = 1
                pos.x = 64
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.uprightwards]
                frame-count = 1
                pos.x = 112
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.upleftwards]
                frame-count = 1
                pos.x = 96
                pos.y = 64
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.downrightwards]
                frame-count = 1
                pos.x = 112
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16
    
            [graphics.mobs.aggressive.downleftwards]
                frame-count = 1
                pos.x = 96
                pos.y = 80
                shift.x = -8
                shift.y = -8
                width = 16
                height = 16

    [graphics.tiles]
        list = ["chasm", "iron-tile", "concrete-tile", "tile-frame"]
        spacing.x = 32
        x-yshift = 0

        spacing.y = 32
        y-xshift = 0

        width = 32
        height = 32

        [graphics.tiles.chasm]
            id = @TILES_CHASMID@
            frame-count = 4
            pos.x = 0
            pos.y = 32

        [graphics.tiles.iron-tile]
            id = @TILES_IRONID@
            frame-count = 1
            pos.x = 32
            pos.y = 0

        [graphics.tiles.concrete-tile]
            id = @TILES_CONCRETEID@
            frame-count = 1
            pos.x = 0
            pos.y = 0

        [graphics.tiles.tile-frame]
            id = @TILES_FRAMEID@
            frame-count = 1
            pos.x = 160
            pos.y = 0

    [graphics.objects]
        list = ["button", "gate", "target", "autoshooter"]

        [graphics.objects.button]
            id = @OBJECTS_BUTTONID@
            frame-count = 1
            pos.x = 65
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.gate]
            id = @OBJECTS_GATEID@
            frame-count = 1
            pos.x = 97
            pos.y = 1
            width = 30
            height = 30
            shift.y = 1
            shift.x = 1

        [graphics.objects.target]
            id = @OBJECTS_TARGETID@
            frame-count = 1
            pos.x = 128
            pos.y = 0
            width = 32
            height = 32
            shift.x = 0
            shift.y = 0

        [graphics.objects.autoshooter]
            id = @OBJECTS_AUTOSHOOTERID@
            frame-count = 1
            pos.x = 128
            pos.y = 32
            width = 32
            height = 32
            shift.x = 0
            shift.y = 0